//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitePlacer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainForm {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainForm() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LitePlacer.MainForm", typeof(MainForm).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string Abs_radioButton_ToolTip {
            get {
                return ResourceManager.GetString("Abs_radioButton.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=346,Y=11}.
        /// </summary>
        public static System.Drawing.Point AppSettings_openFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AppSettings_openFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=354,Y=37}.
        /// </summary>
        public static System.Drawing.Point AppSettings_saveFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AppSettings_saveFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no automatic homing on A axis.
        ///Instead, A should be manually set to 0 position, 
        ///with help of a mark on the big pulley.
        ///You can also jog A to 0 position; this button
        ///will set A coordinate to 0 after that..
        /// </summary>
        public static string Ato0_button_ToolTip {
            get {
                return ResourceManager.GetString("Ato0_button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool B_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("B_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=33,Y=67}.
        /// </summary>
        public static System.Drawing.Point CAD_openFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("CAD_openFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataComponentColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataComponentColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataFootprintColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataFootprintColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataPlacedColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataPlacedColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataRotationMachineColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataRotationMachineColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataRotationNominalColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataRotationNominalColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataValueColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataValueColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataXmachineColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataXmachineColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataXnominalColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataXnominalColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataYmachineColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataYmachineColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CADdataYnominalColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CADdataYnominalColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Capacity_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Capacity_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CapacityColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CapacityColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=435,Y=78}.
        /// </summary>
        public static System.Drawing.Point colorDialog1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("colorDialog1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool CoordinatesForParts_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("CoordinatesForParts_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn51_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn51.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn52_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn52.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn53_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn53.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool dataGridViewTextBoxColumn54_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("dataGridViewTextBoxColumn54.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Double1_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Double1_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Enabled_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Enabled_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool EnabledColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("EnabledColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool FirstX_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("FirstX_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool FirstY_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("FirstY_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=556,Y=78}.
        /// </summary>
        public static System.Drawing.Point FPStimer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("FPStimer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Funct_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Funct_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool G_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("G_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GoA_button_ToolTip {
            get {
                return ResourceManager.GetString("GoA_button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string Goto_button_ToolTip {
            get {
                return ResourceManager.GetString("Goto_button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GotoA_textBox_ToolTip {
            get {
                return ResourceManager.GetString("GotoA_textBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GotoX_textBox_ToolTip {
            get {
                return ResourceManager.GetString("GotoX_textBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GotoY_textBox_ToolTip {
            get {
                return ResourceManager.GetString("GotoY_textBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GotoZ_textBox_ToolTip {
            get {
                return ResourceManager.GetString("GotoZ_textBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GoX_button_ToolTip {
            get {
                return ResourceManager.GetString("GoX_button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GoY_button_ToolTip {
            get {
                return ResourceManager.GetString("GoY_button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string GoZ_button_ToolTip {
            get {
                return ResourceManager.GetString("GoZ_button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Id_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Id_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool IdColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("IdColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Int1_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Int1_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=29,Y=6}.
        /// </summary>
        public static System.Drawing.Point Job_openFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("Job_openFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=32,Y=27}.
        /// </summary>
        public static System.Drawing.Point Job_saveFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("Job_saveFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobdataComponentsColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobdataComponentsColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobdataCountColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobdataCountColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobDataFootprintColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobDataFootprintColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobdataMethodColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobdataMethodColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobdataMethodParametersColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobdataMethodParametersColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobDataNozzleColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobDataNozzleColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool JobDataValueColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("JobDataValueColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera switching methods:
        ///Fast: Uncheck both. Fastest and uses least resources, but may cause issues on some systems
        ///Robust: Check robust, uncheck Keep active. Saves resources,  but slower switch mechanism.
        ///Keep Active: Keeps both cameras live (which may be problematic), doesn&apos;t attempt to switch cameras,
        ///needs more USB and system resources.
        ///
        ///Best and most reliable method is unfortunately system dependent..
        /// </summary>
        public static string KeepActive_checkBox_ToolTip {
            get {
                return ResourceManager.GetString("KeepActive_checkBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera switching methods:
        ///Fast: Uncheck both. Fastest and uses least resources, but may cause issues on some systems
        ///Robust: Check robust, uncheck Keep active. Saves resources,  but slower switch mechanism.
        ///Keep Active: Keeps both cameras live (which may be problematic), doesn&apos;t attempt to switch cameras,
        ///needs more USB and system resources.
        ///
        ///Best and most reliable method is unfortunately system dependent..
        /// </summary>
        public static string label135_ToolTip {
            get {
                return ResourceManager.GetString("label135.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool LastX_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LastX_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool LastY_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("LastY_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=180,Y=69}.
        /// </summary>
        public static System.Drawing.Point MotorPower_timer_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("MotorPower_timer.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Next_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Next_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Next_X_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Next_X_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Next_Y_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Next_Y_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NextPart_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NextPart_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NextX_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NextX_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NextY_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NextY_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Nozzle_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Nozzle_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleCalibrated_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleCalibrated_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=545,Y=18}.
        /// </summary>
        public static System.Drawing.Point NozzleLoad_contextMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("NozzleLoad_contextMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleMaxSize_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleMaxSize_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleMinSize_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleMinSize_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleNo_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleNo_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleNumber_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleNumber_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool NozzleOverrideSize_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("NozzleOverrideSize_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=549,Y=43}.
        /// </summary>
        public static System.Drawing.Point NozzleUnload_contextMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("NozzleUnload_contextMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OffsetX_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("OffsetX_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OffsetY_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("OffsetY_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Orientation_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Orientation_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool OrientationColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("OrientationColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool PickupZ_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PickupZ_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Pitch_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Pitch_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool PlacementMethodColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PlacementMethodColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool PlacementParameterColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PlacementParameterColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool PlaceZ_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("PlaceZ_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool R_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("R_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jog the machine with keyboard:
        ///Numpad arrow keys: unprecise amount
        ///
        ///F key:               With:          Distance:
        ///F5: Left            Alt+Shift:   100 mm / 90 deg.
        ///F6: Right         Alt:              10 mm
        ///F7: Back          Alt+Ctrl:     4 mm
        ///F8: Front         Shift:           1 mm
        ///F9: CCW         None:          0.1 mm
        ///F10: CW          Ctrl:             0.01 mm 
        ///F11: Up
        ///F12: Down.
        /// </summary>
        public static string Relative_Button_ToolTip {
            get {
                return ResourceManager.GetString("Relative_Button.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera switching methods:
        ///Fast: Uncheck both. Fastest and uses least resources, but may cause issues on some systems
        ///Robust: Check robust, uncheck Keep active. Saves resources,  but slower switch mechanism.
        ///Keep Active: Keeps both cameras live (which may be problematic), doesn&apos;t attempt to switch cameras,
        ///needs more USB and system resources.
        ///
        ///Best and most reliable method is unfortunately system dependent..
        /// </summary>
        public static string RobustFast_checkBox_ToolTip {
            get {
                return ResourceManager.GetString("RobustFast_checkBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Rotation_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Rotation_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool RotationColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("RotationColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool RotationDirect_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("RotationDirect_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=796,Y=21}.
        /// </summary>
        public static System.Drawing.Point RunJob_contextMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("RunJob_contextMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool SelectButton_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("SelectButton_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool SelectButtonColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("SelectButtonColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When support asks for &quot;a copy of the log window content&quot;:
        ///Ctrl+A to select all. Then either ctrl+C to copy rich text format
        ///(colors included, preferred method) or ctrl+D to copy plain text without
        ///colors; then paste to a text document..
        /// </summary>
        public static string SerialMonitor_richTextBox_ToolTip {
            get {
                return ResourceManager.GetString("SerialMonitor_richTextBox.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool StartX_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("StartX_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool StartY_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("StartY_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool StartZ_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("StartZ_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=802,Y=44}.
        /// </summary>
        public static System.Drawing.Point Tapes_contextMenuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("Tapes_contextMenuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=173,Y=9}.
        /// </summary>
        public static System.Drawing.Point TapesAll_openFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("TapesAll_openFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=176,Y=33}.
        /// </summary>
        public static System.Drawing.Point TapesAll_saveFileDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("TapesAll_saveFileDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=353,Y=77}.
        /// </summary>
        public static System.Drawing.Point toolTip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Tray_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Tray_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool TrayID_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("TrayID_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Type_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Type_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool TypeColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("TypeColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool UseNozzleCoordinates_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("UseNozzleCoordinates_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool VideoFunctionColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("VideoFunctionColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool VisionAlgorithm_column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("VisionAlgorithm_column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Width_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Width_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool WidthColumn_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("WidthColumn.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool X_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("X_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Y_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Y_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Z_Pickup_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Z_Pickup_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        public static bool Z_Place_Column_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("Z_Place_Column.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
